version: '3'
services:
  url_shortener:
    build: .
    environment:
      MIX_ENV: dev
      ENVIRONMENT: dev
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/server
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
     - "5432:5432"

